name: Dependabot Updates

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
